/*
 * TeacherToolWindow.java
 *
 * Created on January 13, 2007, 3:27 PM
 */

package lambdacalc.gui;

import java.io.*;
import java.util.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.*;
import lambdacalc.exercises.*;

/**
 *
 * @author  tauberer
 */
public class TeacherToolWindow extends javax.swing.JFrame {
    static TeacherToolWindow singleton;
    
    File directory;
    String titleOfShowingExercise;
    
    public static void showWindow() {
        if (singleton == null) {
            singleton = new TeacherToolWindow();
        
            // Ask the user to open a directory immediately,
            // but if user cancels, don't bother showing the window.
            if (!singleton.onOpen()) {
                singleton = null;
                return;
            }
        }
        
        singleton.show();
    }
    
    public static void disposeWindow() {
        if (singleton != null)
            singleton.dispose();
    }
    
    /** Creates new form TeacherToolWindow */
    public TeacherToolWindow() {
        initComponents();

        MainWindow.initializeJFileChooser(fileChooser, false, true);
        
        fileTable.getSelectionModel().addListSelectionListener(new SelectionListener());
        fileTable.getColumnModel().getSelectionModel().addListSelectionListener(new SelectionListener());
        
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        fileChooser = new javax.swing.JFileChooser();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        fileTable = new javax.swing.JTable();
        statsField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jOpenMenuItem = new javax.swing.JMenuItem();
        jExitMenuItem = new javax.swing.JMenuItem();

        fileChooser.setApproveButtonText("Open Directory");
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setTitle("Lambda Teacher Tool");
        jPanel1.setLayout(new java.awt.BorderLayout());

        fileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPanel1.add(fileTable, java.awt.BorderLayout.CENTER);

        statsField.setEditable(false);
        statsField.setText(".... statistics ...");
        jPanel1.add(statsField, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setViewportView(jPanel1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        textArea.setColumns(20);
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Serif", 0, 14));
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textArea);

        jSplitPane1.setRightComponent(jScrollPane2);

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");
        jOpenMenuItem.setMnemonic('O');
        jOpenMenuItem.setText("Open Directory...");
        jOpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenMenuItemActionPerformed(evt);
            }
        });

        jMenu1.add(jOpenMenuItem);

        jExitMenuItem.setMnemonic('x');
        jExitMenuItem.setText("Exit Teacher Tool");
        jExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitMenuItemActionPerformed(evt);
            }
        });

        jMenu1.add(jExitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenMenuItemActionPerformed
        onOpen();
    }
    
    private boolean onOpen() {
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == fileChooser.APPROVE_OPTION) {
            directory = fileChooser.getSelectedFile();
            scanForAssignments();
            if (assignmentList.size() > 0)
                titleOfShowingExercise = (String)assignmentList.get(0);
            showExercises();
            return true;
        }             
        return false;
    }//GEN-LAST:event_jOpenMenuItemActionPerformed

    private void jExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitMenuItemActionPerformed
        this.hide();
    }//GEN-LAST:event_jExitMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherToolWindow().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTable fileTable;
    private javax.swing.JMenuItem jExitMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jOpenMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField statsField;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
    
    
    Vector assignmentList = new Vector();
    Vector exercises = new Vector();
    String tableAsString = "";
   
    // This gets a unique list of the titles of the
    // various exercise files in the directory, so that
    // we can display one assignment (i.e. class of homeworks)
    // at a time.
    private void scanForAssignments() {
        assignmentList.clear();
        File[] files = directory.listFiles();
        for (int i = 0; i < files.length; i++) {
            if (MainWindow.isSerialized(files[i])) {
                try {
                    ExerciseFile ex = new ExerciseFile(files[i]);
                    if (!assignmentList.contains(ex.getTitle()))
                        assignmentList.add(ex.getTitle());
                } catch (Exception e) {
                }
            }
        }
    }
    
    private class ReadOnlyTableModel extends DefaultTableModel {
        public boolean isCellEditable(int x, int y) {
            return false;
        }
    }
    
    private class ExerciseFileListEntry implements Comparable {
    	public File file;
        public ExerciseFile exFile;
        public String errorMessage;
        public int compareTo(Object other) {
            return getSortKey().compareTo(((ExerciseFileListEntry)other).getSortKey());
        }
        String getSortKey() {
            if (exFile == null)
                return file.getName();
            else if (exFile.getStudentName() == null)
            	return "[Unknown]";
            else
            	return exFile.getStudentName();
        }
    }
    
    private void showExercises() {
        // Load the student's work.
        
        // First load in the files so that we can sort them
        // ourself.
        exercises.clear();
        File[] files = directory.listFiles();
        for (int i = 0; i < files.length; i++) {
            if (MainWindow.isSerialized(files[i])) {
                Object[] row = new Object[6];

                ExerciseFileListEntry entry = new ExerciseFileListEntry();
                entry.file = files[i];

                try {
                    ExerciseFile ex = new ExerciseFile(files[i]);
                    if (!ex.getTitle().equals(titleOfShowingExercise))
                    	continue;
                    
                    entry.exFile = ex;
                    
                } catch (Exception e) {
                    entry.errorMessage = e.getMessage();
                }
        
                exercises.add(entry);
            }
        }
        
        Collections.sort(exercises);
        
        // Now put the exercises into a table model
        
        DefaultTableModel model = new ReadOnlyTableModel();
        
        model.addColumn("Student");   // 0
        model.addColumn("Points"); // 1
        model.addColumn("File Name"); // 2
        
        tableAsString = ""; // for copying to clipboard, easier to create now
        
        ArrayList scores = new ArrayList();
        
        for (int i = 0; i < exercises.size(); i++) {
            ExerciseFileListEntry entry = (ExerciseFileListEntry)exercises.get(i);
            
            Object[] row = new Object[6];
            row[2] = entry.file.getName();

            if (entry.exFile != null) {
                row[0] = entry.exFile.getStudentName();
                row[1] = entry.exFile.getPointsCorrect() + "/" + entry.exFile.getTotalPointsAvailable();
                    
                scores.add(entry.exFile.getPointsCorrect());
            } else {
                row[0] = "Error Loading File";
            }
            
            model.addRow(row);
            
            tableAsString = tableAsString + row[0] + "\t" + row[1] + "\t" + row[2] + "\n";
        }
        
        fileTable.setModel(model);
        
        textArea.setText(createAssignmentSummary());
        
        // Compute statistics.
        if (scores.size() == 0)
            statsField.setText("No student files found in this directory.");
        else
            statsField.setText("students: " + scores.size() + "; mean: " + formatDouble(mean(scores)) + "; std-dev: " + formatDouble(stdev(scores)) + "; median: " + formatDouble(median(scores)));
    }
    
    String formatDouble(double d) {
        return "" + Math.round(d * 10.0)/10.0; // round double to one decimal place
    }
    
    double mean(ArrayList scores) {
        double total = 0;
        for (Iterator i = scores.iterator(); i.hasNext(); )
            total += ((java.math.BigDecimal)i.next()).doubleValue();
        return total / (double)scores.size();
    }
    
    double stdev(ArrayList scores) {
        double mean = mean(scores);
        
        double total = 0;
        for (Iterator i = scores.iterator(); i.hasNext(); ) {
            double v = ((java.math.BigDecimal)i.next()).doubleValue() - mean;
            total += v*v;
        }
        return Math.sqrt(total / ((double)scores.size()-1));
    }

    double median(ArrayList scores) {
        ArrayList sortedScores = (ArrayList)scores.clone();
        Collections.sort(sortedScores);
        if (scores.size() % 2 == 1) {
            return ((java.math.BigDecimal)sortedScores.get((scores.size()-1) / 2)).doubleValue();
        } else {
            return (((java.math.BigDecimal)sortedScores.get(scores.size() / 2 - 1)).doubleValue() + ((java.math.BigDecimal)sortedScores.get(scores.size() / 2)).doubleValue())/2.0;
        }
    }

    class SelectionListener implements ListSelectionListener {
        public void valueChanged(ListSelectionEvent e) {
            if (fileTable.getSelectedRow() == -1) { textArea.setText(createAssignmentSummary()); return; }
            ExerciseFileListEntry entry = (ExerciseFileListEntry)exercises.get(fileTable.getSelectedRow());
            showFileDetails(entry.file);
        }
    }
    
    public void showFileDetails(File file) {
        try {
            ExerciseFile exfile = new ExerciseFile(file);
            
            String text = "";
            text += exfile.getTitle() + "\n";
            text += "\n";
            text += "Student: " + exfile.getStudentName() + "\n";
            text += "\n";
            
            text += "Points: " + exfile.getPointsCorrect() + "/" + exfile.getTotalPointsAvailable() + "\n";

            text += "\n";
            
            for (int i = 0; i < exfile.size(); i++) {
                ExerciseGroup g = exfile.getGroup(i);
                
                text += (char)('A' + i) + ". " + g.getTitle() + "\n";
                text += "\n";
                
                java.math.BigDecimal groupPointsTotal = java.math.BigDecimal.valueOf(0);
                java.math.BigDecimal groupPointsCorrect = java.math.BigDecimal.valueOf(0);
                
                for (int j = 0; j < g.size(); j++) {
                    Exercise ex = g.getItem(j);
                    
                    text += "   ";
                    
                    if (!ex.isDone())
                        text += ExerciseTreeModel.BALLOT_EX;
                    else
                        text += ExerciseTreeModel.CHECKMARK;
                    
                    text += "   " + (j+1) + ".  ";

                    text += ex.getExerciseText();
                    text += "\t";
                    
                    if (ex.hasBeenStarted() && !ex.isDone())
                        text += "Student's Last Answer: " + ex.getLastAnswer();
                    
                    text += "\n";
                    
                    groupPointsTotal = groupPointsTotal.add(ex.getPoints());
                    if (ex.isDone())
                        groupPointsCorrect = groupPointsCorrect.add(ex.getPoints());
                }
                
                text += "\n";
                text += "   " + groupPointsCorrect + "/" + groupPointsTotal + " points in this section.\n";
                text += "\n";
            }
            
            textArea.setText(text);
        
        } catch (IOException e) {
            String text = "The file " + file.getPath() + " could not be opened: " + e.toString();
            textArea.setText(text);
            
        } catch (ExerciseFileFormatException e) {
            String text = "The file " + file.getPath() + " could not be opened.  It looks like this isn't a student work file for this program, or a bug in the program prevented the file from being read: " + e.toString();
            textArea.setText(text);
            
        }
    }
    
    String createAssignmentSummary() {
        // This creates a summary of how many students got each question right.
        
        // Use one student's exercise as a template.
        if (exercises.size() == 0) return "No student exercises are loaded.";
        ExerciseFile extempl = ((ExerciseFileListEntry)exercises.get(0)).exFile;
        String text = "Click on an exercise in the table to the left to view the student's details.\n\nAssignment Summary:\n\nEach line reports the number of students who got each question right and wrong.\n\n";
        for (int g = 0; g < extempl.size(); g++) {
            ExerciseGroup group = extempl.getGroup(g);
             
            text += (char)('A' + g) + ". " + group.getTitle() + "\n";
            text += "\n";
                
            for (int j = 0; j < group.size(); j++) {
                Exercise ex = group.getItem(j);
                    
                text += "   ";
                    
                // Loop through each student's work
                int correct = 0, incorrect = 0;
                for (int i = 0; i < exercises.size(); i++) {
                    ExerciseFile exf = ((ExerciseFileListEntry)exercises.get(i)).exFile;
                    if (exf == null) continue;
                    ExerciseGroup gg = exf.getGroup(g);
                    Exercise ee = gg.getItem(j);
                    
                    if (ee.isDone())
                        correct++; 
                    else
                        incorrect++;
                }
                
                text += correct + " right";
                text += "/";
                text += incorrect + " wrong";  
                text += ": ";
                text += ex.getExerciseText();
                text += "\n";
            }
            
            text += "\n";
        }
        
        return text;
    }
    
    public void copyTable() {
        java.awt.datatransfer.StringSelection ss
            = new java.awt.datatransfer.StringSelection(tableAsString);
        try {
            java.awt.Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ss, ss);
        } catch (Exception e) {
            // if copying to clipboard is not supported at this time
        }                
    }
}
